project:
  type: website
  resources: 
    - cv.pdf

website:
  title: "Xianya Fu"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: projects
      
  page-footer: 
    right: "&copy; 2024, Xianya Fu"



format:
  html:
    theme: sketchy
    css: styles.css
    toc: true


execute: 
  freeze: auto


